/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ChatRMI;

import ChatRMI.peer.FinestraChat;
import ChatRMI.peer.GestoreMessaggi;
import ChatRMI.peer.InterfacciaFinestraChat;
import ChatRMI.peer.InterfacciaGestoreMessaggi;

public class App {
    public static void main(String[] args) {

        InterfacciaGestoreMessaggi gestoreMessaggi = new GestoreMessaggi();
        InterfacciaFinestraChat finestraChat = new FinestraChat();
        gestoreMessaggi.legaFinestra(finestraChat);
        finestraChat.legaGestore(gestoreMessaggi);

        
    }
}
